### ISSUE TITLE
Error reading IMP generated RMF files: UsageError: "Can't convert null value." processing decorator of type ParticleConst

### ISSUE THREAD

**Issue by jaredsagendorf** [salilab/rmf_chimerax#1]
Hi, I'm looking at the IMP tutorials and trying to read some generated RMF output files, but keep getting the error (as per ChimeraX log):

```
open pbc_interacting_patches.py.rmf
Cannot open files: UsageError: "Can't convert null value." processing decorator of type ParticleConst
```

I've installed the latest version of both ChimeraX and this plugin, but still the error remains. As for the IMP code, I installed everything from scatch today via Conda.

I am running linux/Fedora 35

**Comment by benmwebb** [comment]
The problem here is that this tutorial creates an RMF file that contains a "Granules" node (this can be seen by running `rmf_show -v` on the file). This node has no attributes except for mass, which makes RMF think it's a `Particle` node. But Particle nodes are also supposed to have coordinates, so RMF gets confused when it tries to extract them and they're not there. The RMF code in Chimera can read this file though, so I'll steal a workaround from there.
